### ISSUE TITLE
TypeError: Object of type 'date' is not JSON serializable

### ISSUE THREAD

**Issue by JackAtOmenApps** [shhaumb/django-scooby-profiler#5]
Running Django 2.1.2, Python 3.6, on Ubuntu 18.04.

After installing scooby, when I go to any URL in my project, I get the following error and stack trace:

> builtins.TypeError
> 
> TypeError: Object of type 'date' is not JSON serializable
> 
> 
> 
> Traceback (most recent call last)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
> 
> return self.application(environ, start_response)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
> 
> response = self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/base.py", line 78, in get_response
> 
> response = self._middleware_chain(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/myproject/myproject/audits/middleware/myprojectaudit.py", line 51, in __call__
> 
> return self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 91, in __call__
> 
> response = response or self.get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
> 
> response = response_for_exception(request, exc)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
> 
> response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
> 
> return debug.technical_500_response(request, *exc_info)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 37, in null_technical_500_response
> 
> six.reraise(exc_type, exc_value, tb)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/six.py", line 693, in reraise
> 
> raise value
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
> 
> response = get_response(request)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/django/utils/deprecation.py", line 93, in __call__
> 
> response = self.process_response(request, response)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/scooby/middleware.py", line 57, in process_response
> 
> backend.set(unique_hex, request.scooby_data.as_json(), 120)
> 
> File "/home/myproject/.local/share/virtualenvs/myproject-Uem2Cohr/lib/python3.6/site-packages/scooby/base.py", line 42, in as_json
> 
> 'plugins_data': plugins_data_json
> 
> File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
> 
> return _default_encoder.encode(obj)
> 
> File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
> 
> chunks = self.iterencode(o, _one_shot=True)
> 
> File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
> 
> return _iterencode(o, 0)
> 
> File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
> 
> o.__class__.__name__)
> 
> TypeError: Object of type 'date' is not JSON serializable
> 
> The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
> 
> To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.
> 
> 
> 
> You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:
> 
> 
> 
> dump() shows all variables in the frame
> 
> dump(obj) dumps all that's known about the object
> 
> Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by shhaumb** [comment]
This is fixed in v2.0.6. Can you check by installing that version?

**Comment by JackAtOmenApps** [comment]
Unfortunately, I still get the same issue. I did make one change in my configuration in addition to upgrading to scooby v2.0.6: I'm now using Python 3.7.1. 

It looks like the trace is essentially the same, with the exception of the final entry:

> File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
>> raise TypeError(f'Object of type {o.__class__.__name__} '

> TypeError: Object of type date is not JSON serializable

[Full Stack Trace](https://dumptext.com/9j0NCSsO)

**Comment by shhaumb** [comment]
The case was missed in earlier fix commit. I have pushed fix in v2.0.7. Please check it again.

**Comment by JackAtOmenApps** [comment]
@shhaumb Perfect! Working great now!

**Comment by shhaumb** [comment]
Thank you.
